export const LOCK_CIRCLE_RADIUS = 50;
export const LOCK_CIRCLE_CIRCUMFERENCE = 2 * Math.PI * LOCK_CIRCLE_RADIUS;
export const LOCK_CIRCLE_STROKE_WIDTH = 10;
export const LOCK_HALF_CIRCLE = LOCK_CIRCLE_RADIUS + LOCK_CIRCLE_STROKE_WIDTH;
export const LOCK_WIDTH = LOCK_CIRCLE_RADIUS * 0.5;
export const LOCK_HEIGHT = LOCK_CIRCLE_RADIUS * 0.8;
